# Generated by Django 2.0.3 on 2018-04-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='Areas.AreaInfo')),
            ],
            options={
                'db_table': 'areainfo',
                'verbose_name': '地区信息',
                'verbose_name_plural': '地区信息',
            },
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areainfo', to='Areas.AreaInfo')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areainfos', to='Areas.AreaInfo')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Areas.AreaInfo')),
            ],
            options={
                'db_table': 'heroinfo',
                'verbose_name': '人物信息',
                'verbose_name_plural': '人物信息',
            },
        ),
    ]
