# Generated by Django 2.0.3 on 2018-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areainfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
